; PlatformIO Project Configuration File for DoorSign
; Board: Seeed Studio XIAO ESP32-S3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Equivalent of Arduino IDE's "Tools > USB CDC On Boot > Enabled"
; Crucial foredits seeing Serial.print outputs over the native USB-C port on this board!
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    ; Force the background network engine to run strictly on Core 1
    ;-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    ; Allocate extra memory safety padding to prevent stack overflows
    ;-D CONFIG_ASYNC_TCP_STACK_SIZE=16384

; Configure the filesystem partition to use LittleFS
board_build.filesystem = littlefs

lib_deps =
    https://github.com/ZinggJM/GxEPD2.git#1.6.9
    adafruit/Adafruit GFX Library
    ricmoo/QRCode
    bblanchon/ArduinoJson @ ^7.0.0
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git